# Generated by Django 5.2.10 on 2026-05-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRelatedParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildWithFK',
            fields=[
                ('childrelatedparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.childrelatedparent')),
                ('related_plain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.plaina')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.childrelatedparent',),
        ),
        migrations.CreateModel(
            name='GrandChildWithFK',
            fields=[
                ('childwithfk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.childwithfk')),
                ('extra_field', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.childwithfk',),
        ),
        migrations.CreateModel(
            name='ChildWithFKAndM2M',
            fields=[
                ('childrelatedparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.childrelatedparent')),
                ('fk_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.modelextraexternal')),
                ('m2m_targets', models.ManyToManyField(blank=True, related_name='child_fk_m2m_set', to='tests.modelextraexternal')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.childrelatedparent',),
        ),
        migrations.CreateModel(
            name='ChildWithM2M',
            fields=[
                ('childrelatedparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.childrelatedparent')),
                ('m2m_plain', models.ManyToManyField(blank=True, related_name='child_m2m_set', to='tests.plaina')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.childrelatedparent',),
        ),
    ]
